import { ArrowUpRight, ExternalLink, FileText, GitBranch, Network, ScanFace } from 'lucide-react'
import type { Project } from '../data/projects'

function ProjectVisual({ project }: { project: Project }) {
  if (project.visual === 'lex') return <div className="project-visual lex-visual"><div className="doc-sheet"><div className="doc-title" /><div className="doc-line" /><div className="doc-line short" /><div className="doc-line" /><div className="doc-chip">SUMMARY</div></div><div className="ai-orbit"><span /><span /><span /><b>RAG</b></div><div className="visual-label"><FileText size={13} /> document intelligence</div></div>
  if (project.visual === 'port') return <div className="project-visual port-visual"><div className="port-stats"><span>VESSELS <b>24</b></span><span>TURNAROUND <b>18.4h</b></span></div><div className="chart-bars">{[34, 58, 43, 74, 52, 81, 66, 92, 73].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><div className="port-route"><span /> <i /> <span /> <i /> <span /></div><div className="visual-label"><GitBranch size={13} /> operations / live demo data</div></div>
  if (project.visual === 'network') return <div className="project-visual network-visual"><svg viewBox="0 0 360 210" role="img" aria-label="Synthetic relationship network"><path d="M40 130 L118 54 L195 111 L278 46 L324 142 M118 54 L278 46 M195 111 L324 142 M40 130 L195 111" /><circle cx="40" cy="130" r="9" /><circle cx="118" cy="54" r="14" /><circle cx="195" cy="111" r="20" /><circle cx="278" cy="46" r="11" /><circle cx="324" cy="142" r="13" /><text x="107" y="87">ORG</text><text x="181" y="147">ENTITY</text></svg><div className="visual-label"><Network size={13} /> synthetic relationship graph</div></div>
  return <div className="project-visual dossier-visual"><div className="hud-corner hud-tl" /><div className="hud-corner hud-br" /><div className="face-frame"><span /><span /><span /><span /><ScanFace size={42} /></div><div className="dossier-copy"><b>CONFIDENTIAL DOSSIER</b><span>NEURAL TRACE v5.2</span><span className="match"><i /> MATCH FOUND</span></div><div className="visual-label">CAMERA FEED // DEMO SUBJECT</div></div>
}

export function ProjectCard({ project, index }: { project: Project; index: number }) {
  return <article className={`project-card accent-${project.accent} reveal`}><div className="project-index">0{index + 1}</div><ProjectVisual project={project} /><div className="project-content"><p className="project-category">{project.category}</p><h3>{project.name}</h3><p className="project-description">{project.description}</p><div className="project-tags">{project.technologies.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-actions"><a href={project.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14} /></a><a href={project.demo}>{project.demo === '#contact' ? 'Discuss project' : 'Live demo'} <ExternalLink size={14} /></a></div></div></article>
}
